### ISSUE TITLE
create a proper README

### ISSUE THREAD

**Issue by CheesyPhoenix** [CheesyPhoenix/BetterSchool#3]

**Comment by Osha80** [comment]
Hello CheesyPhoenixis is this task still open?
Can you clarify more what you mean or expectations of a  proper README.md file?
I am interested in tasking this task.

**Comment by Osha80** [comment]
![image](https://user-images.githubusercontent.com/18071892/186039597-9269174c-23d1-49d7-b5ec-b75b0ed2d7df.png)

**Comment by Osha80** [comment]
![repo](https://user-images.githubusercontent.com/18071892/186039686-9939ca89-3a5b-470f-841b-cac3d01f02b0.jpg)

I done that locally

**Comment by AndyCoolDude** [comment]
How did you find this project friend?

**Comment by CheesyPhoenix** [comment]
You clearly do not know what this project is about @Osha80

**Comment by CheesyPhoenix** [comment]
Better but still open for additions

**Comment by Osha80** [comment]
> You clearly do not know what this project is about @Osha80

If you will be please tell me project scope.
Yes I am just learning about Open source and found project online on https://goodfirstissues.com/ and thought I could give it a try. Please let me know what I could have done better.

**Comment by CheesyPhoenix** [comment]
If you are looking for a good first open-source project to comtribute to, this is not the one for you. This is a project with an incredibly small potential userbase, and an even smaller actual userbase. In addittion the project can only be used by students of a specific school, and therefore is not a good project to contribute to for people not attending said school. @Osha80

**Comment by Osha80** [comment]
okay noted with thanks, I will explore elsewhere. Thanks for your time
